# Generated by Django 5.0.6 on 2024-05-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('description', models.TextField(max_length=255, verbose_name='description')),
                ('tag', models.CharField(max_length=60, verbose_name='tag')),
                ('url', models.URLField(verbose_name='link')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Medias',
            },
        ),
        migrations.CreateModel(
            name='MainSMImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
                ('image', models.ImageField(upload_to='MainSM/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Social Media Image',
                'verbose_name_plural': 'Social Media Images',
            },
        ),
    ]
