# Generated by Django 5.0.6 on 2024-05-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_mainsm_mainsmimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsm',
            name='image',
            field=models.ManyToManyField(related_name='socialmedias', to='pages.mainsmimage', verbose_name='image'),
        ),
    ]
