# Generated by Django 5.0.6 on 2024-06-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_mainsm_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsmimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='MainSM/', verbose_name='image'),
        ),
    ]
