# Generated by Django 5.0.6 on 2024-06-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_mainsmimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsmimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mainsmimage',
            name='updated_at',
        ),
    ]
