# Generated by Django 5.0.6 on 2024-06-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_mainsmimage_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsm',
            name='image',
        ),
    ]
