# Generated by Django 5.0.6 on 2024-05-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Products'},
        ),
        migrations.AlterModelTable(
            name='productmodel',
            table='Products',
        ),
    ]
