# Generated by Django 5.0.6 on 2024-05-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productmodel_options_alter_productmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmodel',
            table='Shop product',
        ),
    ]
