# Generated by Django 5.0.6 on 2024-05-12 13:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='long_description',
            field=ckeditor.fields.RichTextField(verbose_name='long description'),
        ),
    ]
