# Generated by Django 5.0.6 on 2024-05-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productmodel_long_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmodel',
            options={'verbose_name': 'Brand', 'verbose_name_plural': '3. Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': '2. Categories'},
        ),
        migrations.AlterModelOptions(
            name='colormodel',
            options={'verbose_name': 'Color', 'verbose_name_plural': '5. Colors'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product', 'verbose_name_plural': '1. Products'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': '6. Tags'},
        ),
        migrations.AlterModelOptions(
            name='sizemodel',
            options={'verbose_name': 'Size', 'verbose_name_plural': '4. Sizes'},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='long_description',
            field=models.TextField(verbose_name='long description'),
        ),
    ]
